baseURL = "https://ll.sc.cn"
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 主题
# theme = "LoveIt"
theme = ["hugo-search-fuse-js", "LoveIt"]

# 网站标题
title = "雷雷的个人博客"

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true
# 是否包括中日韩文字
hasCJKLanguage = true
# 默认每页列表显示的文章数目
paginate = 12
# [UA-XXXXXXXX-X] 谷歌分析代号
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# 菜单配置
[menu]
  [[menu.main]]
  identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fas fa-fw fa-archive'></i>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "归档"
    url = "/posts/"
    title = "所有文章"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    pre = "<i class='fas fa-folder-open'></i>"
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    # 二级菜单
    [[menu.main]]
      parent = "categories"
      identifier = "work"
      pre = "<i class='fas fa-briefcase'></i>"
      post = ""
      name = "爱工作"
      url = "/categories/work/"
      title = ""
      weight = 1
    [[menu.main]]
      parent = "categories"
      identifier = "study"
      pre = "<i class='fas fa-graduation-cap'></i>"
      post = ""
      name = "爱学习"
      url = "/categories/study/"
      title = ""
      weight = 2
    [[menu.main]]
      parent = "categories"
      identifier = "z-turn"
      pre = "<i class='fas fa-tools'></i>"
      post = ""
      name = "爱折腾"
      url = "/categories/z-turn/"
      title = ""
      weight = 3
    [[menu.main]]
      parent = "categories"
      identifier = "windows"
      pre = "<i class='fab fa-windows'></i>"
      post = ""
      name = "Windows"
      url = "/categories/windows/"
      title = ""
      weight = 4
    [[menu.main]]
      parent = "categories"
      identifier = "software"
      pre = "<i class='fab fa-app-store-ios'></i>"
      post = ""
      name = "软件类"
      url = "/categories/software/"
      title = ""
      weight = 4
    [[menu.main]]
      parent = "categories"
      identifier = "record"
      pre = "<i class='fas fa-box'></i>"
      post = ""
      name = "杂　记"
      url = "/categories/record/"
      title = ""
      weight = 5

  [[menu.main]]
    identifier = "tags"
    pre = "<i class='fas fa-tags'></i>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "Post"
    pre = "<i class='fas fa-atom fa-spin'></i>"
    post = ""
    name = "动态"
    url = ""
    title = ""
    weight = 4
    # 二级菜单
    [[menu.main]]
      parent = "Post"
      identifier = "journal"
      pre = "<i class='fas fa-comment'></i>"
      post = ""
      name = "日　志"
      url = "/journal/"
      title = ""
      weight = 1
    [[menu.main]]
      parent = "Post"
      identifier = "Moments"
      pre = "<i class='fas fa-comments'></i>"
      post = ""
      name = "时　刻"
      url = "/Moments/"
      title = ""
      weight = 2
    [[menu.main]]
      parent = "Post"
      identifier = "board"
      pre = "<i class='fas fa-clipboard'></i>"
      post = ""
      name = "留　言"
      url = "/board/"
      title = ""
      weight = 3
  [[menu.main]]
    identifier = "link"
    pre = "<i class='fas fa-link'></i>"
    name = "链接"
    url = ""
    title = ""
    weight = 5
    # 二级菜单
    [[menu.main]]
      parent = "link"
      identifier = "friend"
      pre = "<i class='fas fa-user-friends'></i>"
      name = "友情链接"
      url = "/friend/"
      title = ""
      weight = 1
    [[menu.main]]
      parent = "link"
      identifier = "book"
      pre = "<i class='fas fa-book'></i>"
      post = ""
      name = "我的书单"
      url = "/book/"
      title = ""
      weight = 2
    [[menu.main]]
      parent = "link"
      identifier = "china_map"
      pre = "<i class='fas fa-map'></i>"
      post = ""
      name = "我的足迹"
      url = "/china_map/"
      title = ""
      weight = 3
    [[menu.main]]
      parent = "link"
      identifier = "links"
      pre = "<i class='fas fa-globe-asia'></i>"
      post = ""
      name = "常用站点"
      url = "/links/"
      title = ""
      weight = 4
  
  # [[menu.main]]
  #   identifier = "mirror"
  #   pre = "<i class='fas fa-inbox'></i>"
  #   name = "镜像"
  #   url = ""
  #   title = ""
  #   weight = 6
  #   # 二级菜单
  #   [[menu.main]]
  #     parent = "mirror"
  #     identifier = "gitee"
  #     pre = "<i class='fab fa-goodreads'></i>"
  #     post = "_blank"
  #     name = "Gitee站"
  #     url = "https://cajunlei.gitee.io/"
  #     title = ""
  #     weight = 1
  #   [[menu.main]]
  #     parent = "mirror"
  #     identifier = "github"
  #     pre = "<i class='fab fa-github-square'></i>"
  #     post = "_blank"
  #     name = "Github站"
  #     url = "https://cajunlei.github.io/"
  #     title = ""
  #     weight = 2
  #   [[menu.main]]
  #     parent = "mirror"
  #     identifier = "Vercel"
  #     pre = "<i class='fas fa-caret-square-up'></i>"
  #     post = "_blank"
  #     name = "Vercel站"
  #     url = "https://cajunlei-github-io-cajunlei.vercel.app"
  #     title = ""
  #     weight = 3

  [[menu.main]]
    identifier = "about"
    pre = "<i class='fas fa-user'></i>"
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 9
  [[menu.main]]
    identifier = "travellings"
    pre = "<i class='fas fa-subway'></i>"
    post = ""
    name = "开往"
    url = "https://travellings.cn"
    title = "开往-友链接力"
    weight = 10
[params]
  # 网站描述
  description = "爱生活，爱工作，爱折腾"
  # 网站关键词
  keywords = ["Design", "Building", "设计", "雷雷"]
  # LoveIt 主题版本
  version = "0.2.X"
  # 网站默认主题 ("light", "dark", "auto")
  defaultTheme = "light"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/cajunlei/cajunlei.github.io"
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # 日期格式
  dateFormat = "2006-01-02"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/images/logo.webp"]
  # cdn变量，末尾不需要加/
  # cdnPrefix = "https://gitee.com/cajunlei/ImageBed/raw/main"
  # cdnPrefix = "https://cdn.jsdelivr.net/gh/cajunlei/ImageBed"
  # cdnPrefix = "https://cdn.jsdelivr.net/gh/cajunlei/ImageBed@main"  
  # cdnPrefix = "/ImageBed"
  # cdnPrefix = "https://f004.backblazeb2.com/file/ll-blog"
  cdnPrefix = "https://cdn.chiga.ga"
  # cdnPrefix = "https://cdn.chiga.ga/file/ll-blog"
 
  # 不蒜子统计
  busuanzi = true
  busuanzi_site_offset = 100000
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "雷雷屋头"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # 最大结果数目
    maxResultLength = 10
    # 结果内容片段长度
    snippetLength = 50
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
  [params.search.algolia]
    index = "index"
    appID = "GQDBYZDWLG"
    searchKey = "31f3b432d4c23d621a13f434db81e49c"
  
  # 主页信息设置    
  [params.home]
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/images/avatar.webp"
      # 主页显示的网站标题 (支持 HTML 格式)
      title = ""
      # 主页显示的网站副标题
      subtitle = "爱生活-爱工作-爱折腾"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 10
  [params.social]
    GitHub = "cajunlei"
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = "" # cajunray
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = "cajunlei"
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = "" # 输入ID号21018740
    jianshu = "" # 4a52bc63f263
    Email = "i@ll.sc.cn"
    RSS = true
  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
    # 页面头部导航栏标题配置
  [params.header.title]
    # LOGO 的 URL
    logo = ""
    # 标题名称
    name = "雷雷屋头"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fas fa-infinity'></i>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # 是否为标题显示打字机动画
    typeit = false
  # 页面底部信息配置
  [params.footer]
    enable = true
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # 是否显示 Hugo 和主题信息
    hugo = true
    # 是否显示版权信息
    copyright = true
    # 是否显示作者
    author = true
    # 网站创立年份
    since = 2021
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/deed.zh" target="_blank">CC BY-NC 4.0</a>'
  # Section (所有文章) 页面配置
  [params.section]
    # 显示最近更新文章的数量
    lastUpdatedSize = 8
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 文章页面配置
  [params.page]
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = true
    # 是否使用 ruby 扩展语法
    ruby = true
    # 是否使用 fraction 扩展语法
    fraction = true
    # 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = false
    # 是否在 RSS 中显示全文内容
    rssFullText = false
    # 目录配置
    [params.page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
    # Code config
    # 代码配置
    [params.page.code]
    # 是否显示代码块的复制按钮
    copy = true
    # 默认展开显示的代码行数
    maxShownLines = 20
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)
    [params.page.math]
    enable = true
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # 默认行内定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX 插件 mhchem
    mhchem = true
    # Mapbox GL JS 配置 (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
    # Mapbox GL JS 的 access token
    accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
    # 浅色主题的地图样式
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    # 深色主题的地图样式
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    # 是否添加 NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    navigation = true
    # 是否添加 GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    geolocate = true
    # 是否添加 ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    scale = true
    # 是否添加 FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    fullscreen = true
    # 文章页面的分享信息设置
    [params.page.share]
    enable = true
    Twitter = false
    Facebook = false
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = false
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = false
    Instapaper = false
    Pocket = false
    Digg = false
    Stumbleupon = false
    Flipboard = false
    Weibo = true
    Renren = false
    Myspace = false
    Blogger = false
    Baidu = true
    Odnoklassniki = false
    Evernote = true
    Skype = false
    Trello = false
    Mix = false
    # 评论系统设置
    [params.page.comment]
    enable = true
    # Disqus 评论系统设置 (https://disqus.com/)
    [params.page.comment.disqus]
      enable = false
      # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
      shortname = ""
    # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
    [params.page.comment.gitalk]
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Twikoo 评论主页 (https://twikoo.js.org/)
    [params.page.comment.twikoo]
      enable = true
      envId= 'https://blog-twikoo-alpha.vercel.app/'
      el= '#tcomment'
      # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数
      region= ''
      # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
      path= ''
      # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/dev/src/js/utils/i18n/index.js
      lang= ''
    # Valine 评论系统设置 (https://github.com/xCss/Valine)
    [params.page.comment.valine]
      enable = false
      # 从LeanCloud的应用中得到的appId
      appId = "LNjjKgT0YT8BjMthoGsILzWO-MdYXbMMI"
      # 从LeanCloud的应用中得到的appKey
      appKey = "ipeUQBiqi6zIR03tmefFQugf"
      # 评论框占位提示符
      placeholder = ""
      # Gravatar 头像展示方式
      avatar = "robohash"
      # 评论者相关属性
      meta= ""
      # 标识字段名
      tagMeta= ["博主", "小伙伴", "访客"]
      pageSize = 10
      # 多语言支持
      lang = ""
      # 文章访问量统计
      visitor = true
      # 是否记录评论者IP
      recordIP = true
      # 代码高亮
      highlight = true
      # 是否启用昵称框自动获取QQ昵称和QQ头像
      enableQQ = true
      serverURLs = "https://lnjjkgt0.api.lncldglobal.com"
      # 阅读量统计
      el = '#vcomments'
      # emoji 数据文件名称, 默认是 "google.yml"
      # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
      # 位于 "themes/LoveIt/assets/data/emoji/" 目录
      # 可以在你的项目下相同路径存放你自己的数据文件:
      # "assets/data/emoji/"
      emoji = ""
    # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""
    # Telegram comments 评论系统设置 (https://comments.app/)
    [params.page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
    # Commento comment 评论系统设置 (https://commento.io/)
    [params.page.comment.commento]
      enable = false
    # Utterances comment 评论系统设置 (https://utteranc.es/)
    [params.page.comment.utterances]
      enable = false
      # owner/repo
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # 第三方库配置
    [params.page.library]
    [params.page.library.css]
      # someCSS = "some.css"
      # located in "assets/" 位于 "assets/"
      # Or 或者
      # someCSS = "https://cdn.example.com/some.css"
    [params.page.library.js]
      # someJavascript = "some.js"
      # located in "assets/" 位于 "assets/"
      # Or 或者
      # someJavascript = "https://cdn.example.com/some.js"
    # Page SEO config
    # 页面 SEO 配置
    [params.page.seo]
    # 图片 URL
    images = []
    # 出版者信息
    [params.page.seo.publisher]
      name = "守正"
      logoUrl = "/images/avatar.webp"

  # TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = "google699009ae438f1e4d"
    bing = "0AA62D35A93C9239B95F5187EC12FAF1"
    yandex = ""
    pinterest = ""
    baidu = "3f7de7fba11a61559c21d907904d0a1b"
    sogou = "VgMMts5sWb"
    Threesixzero = "8eda9335dc386f7c204d42bfe6c012da"

  # 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

  # 网站分析配置
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""
    # 百度统计
    [params.analytics.baidu]
      id = "37eb9d4da1f3a0120c43a02428b8f5cf"


  # Cookie 许可配置
  [params.cookieconsent]
    enable = false
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

  # 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ("jsdelivr.yml")
    # 位于 "themes/LoveIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

  # 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

  # 在文章末尾显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = true
    # 如果文章最后更新于这天数之前，显示提醒
    hint = 90
    # 如果文章最后更新于这天数之前，显示警告
    warn = 180
  # 文章打赏
  [params.reward]
    enable = true
    # 微信二维码
    wechat = "/reward/wechat.webp"
    # 支付宝二维码         
    alipay = "/reward/alipay.webp"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
    [markup.goldmark.renderer]
    # 是否在文档中直接使用 HTML 标签
    unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = true

# 作者配置
[author]
  name = "守 正"
  email = "i@ll.sc.cn"
  link = "https://ll.sc.cn"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "/posts/:slug/"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  # Google Analytics 相关隐私 (被 params.analytics.google 替代)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
# 用于输出 Algolia 格式文档的设置
[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS", "JSON", "Algolia"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
# minify压缩属性
minify = true
